const AUDIT_ACTION = {
  MEMBER_INVITED: "MEMBER_INVITED",
  MEMBER_ACCEPTED: "MEMBER_ACCEPTED",
  MEMBER_REMOVED: "MEMBER_REMOVED",
  ROLE_CHANGED: "ROLE_CHANGED",
  OWNERSHIP_TRANSFERRED: "OWNERSHIP_TRANSFERRED",
  ORG_CREATED: "ORG_CREATED",
  ORG_UPDATED: "ORG_UPDATED",
  BILLING_CHECKOUT: "BILLING_CHECKOUT",
  BILLING_PLAN_CHANGED: "BILLING_PLAN_CHANGED",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
} as const;

type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];

export { AUDIT_ACTION };

export type { AuditAction };
